INSERT INTO City VALUES ('', 'Abrantes', 193, 'PT');
INSERT INTO City VALUES ('', 'Agualva-Cacém', 193, 'PT');
INSERT INTO City VALUES ('', 'Águeda', 193, 'PT');
INSERT INTO City VALUES ('', 'Albufeira', 193, 'PT');
INSERT INTO City VALUES ('', 'Alcácer do Sal', 193, 'PT');
INSERT INTO City VALUES ('', 'Alcobaça', 193, 'PT');
INSERT INTO City VALUES ('', 'Alfena', 193, 'PT');
INSERT INTO City VALUES ('', 'Almada', 193, 'PT');
INSERT INTO City VALUES ('', 'Almeirim', 193, 'PT');
INSERT INTO City VALUES ('', 'Amadora', 193, 'PT');
INSERT INTO City VALUES ('', 'Amarante', 193, 'PT');
INSERT INTO City VALUES ('', 'Amora', 193, 'PT');
INSERT INTO City VALUES ('', 'Anadia', 193, 'PT');
INSERT INTO City VALUES ('', 'Angra do Heroísmo', 193, 'PT');
INSERT INTO City VALUES ('', 'Aveiro', 193, 'PT');
INSERT INTO City VALUES ('', 'Barcelos', 193, 'PT');
INSERT INTO City VALUES ('', 'Barreiro', 193, 'PT');
INSERT INTO City VALUES ('', 'Beja', 193, 'PT');
INSERT INTO City VALUES ('', 'Braga', 193, 'PT');
INSERT INTO City VALUES ('', 'Bragança', 193, 'PT');
INSERT INTO City VALUES ('', 'Caldas da Rainha', 193, 'PT');
INSERT INTO City VALUES ('', 'Câmara de Lobos', 193, 'PT');
INSERT INTO City VALUES ('', 'Caniço', 193, 'PT');
INSERT INTO City VALUES ('', 'Catanhede', 193, 'PT');
INSERT INTO City VALUES ('', 'Cartaxo', 193, 'PT');
INSERT INTO City VALUES ('', 'Castelo Branco', 193, 'PT');
INSERT INTO City VALUES ('', 'Chaves', 193, 'PT');
INSERT INTO City VALUES ('', 'Coimbra', 193, 'PT');
INSERT INTO City VALUES ('', 'Costa da Caparica', 193, 'PT');
INSERT INTO City VALUES ('', 'Covilhã', 193, 'PT');
INSERT INTO City VALUES ('', 'Elvas', 193, 'PT');
INSERT INTO City VALUES ('', 'Entroncamento', 193, 'PT');
INSERT INTO City VALUES ('', 'Ermesinde', 193, 'PT');
INSERT INTO City VALUES ('', 'Esmoriz', 193, 'PT');
INSERT INTO City VALUES ('', 'Espinho', 193, 'PT');
INSERT INTO City VALUES ('', 'Esposende', 193, 'PT');
INSERT INTO City VALUES ('', 'Estarreja', 193, 'PT');
INSERT INTO City VALUES ('', 'Estremoz', 193, 'PT');
INSERT INTO City VALUES ('', 'Évora', 193, 'PT');
INSERT INTO City VALUES ('', 'Fafe', 193, 'PT');
INSERT INTO City VALUES ('', 'Faro', 193, 'PT');
INSERT INTO City VALUES ('', 'Fátima', 193, 'PT');
INSERT INTO City VALUES ('', 'Felgueiras', 193, 'PT');
INSERT INTO City VALUES ('', 'Figueira da Foz', 193, 'PT');
INSERT INTO City VALUES ('', 'Fiães', 193, 'PT');
INSERT INTO City VALUES ('', 'Freamunde', 193, 'PT');
INSERT INTO City VALUES ('', 'Funchal', 193, 'PT');
INSERT INTO City VALUES ('', 'Fundão', 193, 'PT');
INSERT INTO City VALUES ('', 'Gafanha da Nazaré', 193, 'PT');
INSERT INTO City VALUES ('', 'Gandra', 193, 'PT');
INSERT INTO City VALUES ('', 'Gondomar', 193, 'PT');
INSERT INTO City VALUES ('', 'Gouveia', 193, 'PT');
INSERT INTO City VALUES ('', 'Guarda', 193, 'PT');
INSERT INTO City VALUES ('', 'Guimarães', 193, 'PT');
INSERT INTO City VALUES ('', 'Horta', 193, 'PT');
INSERT INTO City VALUES ('', 'Ílhavo', 193, 'PT');
INSERT INTO City VALUES ('', 'Lagoa', 193, 'PT');
INSERT INTO City VALUES ('', 'Lagos', 193, 'PT');
INSERT INTO City VALUES ('', 'Lamego', 193, 'PT');
INSERT INTO City VALUES ('', 'Leiria', 193, 'PT');
INSERT INTO City VALUES ('', 'Lisboa', 193, 'PT');
INSERT INTO City VALUES ('', 'Lixa', 193, 'PT');
INSERT INTO City VALUES ('', 'Loulé', 193, 'PT');
INSERT INTO City VALUES ('', 'Loures', 193, 'PT');
INSERT INTO City VALUES ('', 'Lourosa', 193, 'PT');
INSERT INTO City VALUES ('', 'Macedo de Cavaleiros', 193, 'PT');
INSERT INTO City VALUES ('', 'Machico', 193, 'PT');
INSERT INTO City VALUES ('', 'Maia', 193, 'PT');
INSERT INTO City VALUES ('', 'Mangualde', 193, 'PT');
INSERT INTO City VALUES ('', 'Marco de Canaveses', 193, 'PT');
INSERT INTO City VALUES ('', 'Marinha Grande', 193, 'PT');
INSERT INTO City VALUES ('', 'Matosinhos', 193, 'PT');
INSERT INTO City VALUES ('', 'Mealhada', 193, 'PT');
INSERT INTO City VALUES ('', 'Mêda', 193, 'PT');
INSERT INTO City VALUES ('', 'Miranda do Douro', 193, 'PT');
INSERT INTO City VALUES ('', 'Mirandela', 193, 'PT');
INSERT INTO City VALUES ('', 'Montemor-o-Novo', 193, 'PT');
INSERT INTO City VALUES ('', 'Montijo', 193, 'PT');
INSERT INTO City VALUES ('', 'Moura', 193, 'PT');
INSERT INTO City VALUES ('', 'Odivelas', 193, 'PT');
INSERT INTO City VALUES ('', 'Olhão', 193, 'PT');
INSERT INTO City VALUES ('', 'Oliveira de Azeméis', 193, 'PT');
INSERT INTO City VALUES ('', 'Oliveira do Bairro', 193, 'PT');
INSERT INTO City VALUES ('', 'Oliveira do Hospital', 193, 'PT');
INSERT INTO City VALUES ('', 'Ourém', 193, 'PT');
INSERT INTO City VALUES ('', 'Ovar', 193, 'PT');
INSERT INTO City VALUES ('', 'Paços de Ferreira', 193, 'PT');
INSERT INTO City VALUES ('', 'Paredes', 193, 'PT');
INSERT INTO City VALUES ('', 'Penafiel', 193, 'PT');
INSERT INTO City VALUES ('', 'Peniche', 193, 'PT');
INSERT INTO City VALUES ('', 'Peso da Régua', 193, 'PT');
INSERT INTO City VALUES ('', 'Pinhel', 193, 'PT');
INSERT INTO City VALUES ('', 'Pombal', 193, 'PT');
INSERT INTO City VALUES ('', 'Ponta Delgada', 193, 'PT');
INSERT INTO City VALUES ('', 'Ponte de Sor', 193, 'PT');
INSERT INTO City VALUES ('', 'Portalegre', 193, 'PT');
INSERT INTO City VALUES ('', 'Portimão', 193, 'PT');
INSERT INTO City VALUES ('', 'Porto', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Baleira', 193, 'PT');
INSERT INTO City VALUES ('', 'Póvoa de Santa Iria', 193, 'PT');
INSERT INTO City VALUES ('', 'Póvoa de Varzim', 193, 'PT');
INSERT INTO City VALUES ('', 'Praia da Vitória', 193, 'PT');
INSERT INTO City VALUES ('', 'Quarteira', 193, 'PT');
INSERT INTO City VALUES ('', 'Queluz', 193, 'PT');
INSERT INTO City VALUES ('', 'Rebordosa', 193, 'PT');
INSERT INTO City VALUES ('', 'Reguengos de Monsaraz', 193, 'PT');
INSERT INTO City VALUES ('', 'Ribeira Grande', 193, 'PT');
INSERT INTO City VALUES ('', 'Rio Maior', 193, 'PT');
INSERT INTO City VALUES ('', 'Rio Tinto', 193, 'PT');
INSERT INTO City VALUES ('', 'Sabugal', 193, 'PT');
INSERT INTO City VALUES ('', 'Sacavém', 193, 'PT');
INSERT INTO City VALUES ('', 'Santa Comba Dão', 193, 'PT');
INSERT INTO City VALUES ('', 'Santa Cruz', 193, 'PT');
INSERT INTO City VALUES ('', 'Santa Maria da Feira', 193, 'PT');
INSERT INTO City VALUES ('', 'Santana', 193, 'PT');
INSERT INTO City VALUES ('', 'Santarém', 193, 'PT');
INSERT INTO City VALUES ('', 'Santiago do Cacém', 193, 'PT');
INSERT INTO City VALUES ('', 'Santo Tirso', 193, 'PT');
INSERT INTO City VALUES ('', 'São João da Madeira', 193, 'PT');
INSERT INTO City VALUES ('', 'São Mamede de Infesta', 193, 'PT');
INSERT INTO City VALUES ('', 'São Salvador de Lordelo', 193, 'PT');
INSERT INTO City VALUES ('', 'Seia', 193, 'PT');
INSERT INTO City VALUES ('', 'Seixal', 193, 'PT');
INSERT INTO City VALUES ('', 'Serpa', 193, 'PT');
INSERT INTO City VALUES ('', 'Setúbal', 193, 'PT');
INSERT INTO City VALUES ('', 'Silves', 193, 'PT');
INSERT INTO City VALUES ('', 'Sines', 193, 'PT');
INSERT INTO City VALUES ('', 'Tarouca', 193, 'PT');
INSERT INTO City VALUES ('', 'Tavira', 193, 'PT');
INSERT INTO City VALUES ('', 'Tomar', 193, 'PT');
INSERT INTO City VALUES ('', 'Tondela', 193, 'PT');
INSERT INTO City VALUES ('', 'Torres Novas', 193, 'PT');
INSERT INTO City VALUES ('', 'Torres Vedras', 193, 'PT');
INSERT INTO City VALUES ('', 'Trancoso', 193, 'PT');
INSERT INTO City VALUES ('', 'Trofa', 193, 'PT');
INSERT INTO City VALUES ('', 'Valbom', 193, 'PT');
INSERT INTO City VALUES ('', 'Vale de Cambra', 193, 'PT');
INSERT INTO City VALUES ('', 'Valongo', 193, 'PT');
INSERT INTO City VALUES ('', 'Valpanços', 193, 'PT');
INSERT INTO City VALUES ('', 'Vendas Novas', 193, 'PT');
INSERT INTO City VALUES ('', 'Viana do Castelo', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila do Conde', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Franca de Xira', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Nova de Famalicão', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Nova de Foz Côa', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Nova de Gaia', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Nova de Santo André', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Real', 193, 'PT');
INSERT INTO City VALUES ('', 'Vila Real de Santo António', 193, 'PT');
INSERT INTO City VALUES ('', 'Viseu', 193, 'PT');
INSERT INTO City VALUES ('', 'Vizela', 193, 'PT');
INSERT INTO City VALUES ('', 'Abrantes', 193, 'EN');
INSERT INTO City VALUES ('', 'Agualva-Cacém', 193, 'EN');
INSERT INTO City VALUES ('', 'Águeda', 193, 'EN');
INSERT INTO City VALUES ('', 'Albufeira', 193, 'EN');
INSERT INTO City VALUES ('', 'Alcácer do Sal', 193, 'EN');
INSERT INTO City VALUES ('', 'Alcobaça', 193, 'EN');
INSERT INTO City VALUES ('', 'Alfena', 193, 'EN');
INSERT INTO City VALUES ('', 'Almada', 193, 'EN');
INSERT INTO City VALUES ('', 'Almeirim', 193, 'EN');
INSERT INTO City VALUES ('', 'Amadora', 193, 'EN');
INSERT INTO City VALUES ('', 'Amarante', 193, 'EN');
INSERT INTO City VALUES ('', 'Amora', 193, 'EN');
INSERT INTO City VALUES ('', 'Anadia', 193, 'EN');
INSERT INTO City VALUES ('', 'Angra do Heroísmo', 193, 'EN');
INSERT INTO City VALUES ('', 'Aveiro', 193, 'EN');
INSERT INTO City VALUES ('', 'Barcelos', 193, 'EN');
INSERT INTO City VALUES ('', 'Barreiro', 193, 'EN');
INSERT INTO City VALUES ('', 'Beja', 193, 'EN');
INSERT INTO City VALUES ('', 'Braga', 193, 'EN');
INSERT INTO City VALUES ('', 'Bragança', 193, 'EN');
INSERT INTO City VALUES ('', 'Caldas da Rainha', 193, 'EN');
INSERT INTO City VALUES ('', 'Câmara de Lobos', 193, 'EN');
INSERT INTO City VALUES ('', 'Caniço', 193, 'EN');
INSERT INTO City VALUES ('', 'Catanhede', 193, 'EN');
INSERT INTO City VALUES ('', 'Cartaxo', 193, 'EN');
INSERT INTO City VALUES ('', 'Castelo Branco', 193, 'EN');
INSERT INTO City VALUES ('', 'Chaves', 193, 'EN');
INSERT INTO City VALUES ('', 'Coimbra', 193, 'EN');
INSERT INTO City VALUES ('', 'Costa da Caparica', 193, 'EN');
INSERT INTO City VALUES ('', 'Covilhã', 193, 'EN');
INSERT INTO City VALUES ('', 'Elvas', 193, 'EN');
INSERT INTO City VALUES ('', 'Entroncamento', 193, 'EN');
INSERT INTO City VALUES ('', 'Ermesinde', 193, 'EN');
INSERT INTO City VALUES ('', 'Esmoriz', 193, 'EN');
INSERT INTO City VALUES ('', 'Espinho', 193, 'EN');
INSERT INTO City VALUES ('', 'Esposende', 193, 'EN');
INSERT INTO City VALUES ('', 'Estarreja', 193, 'EN');
INSERT INTO City VALUES ('', 'Estremoz', 193, 'EN');
INSERT INTO City VALUES ('', 'Évora', 193, 'EN');
INSERT INTO City VALUES ('', 'Fafe', 193, 'EN');
INSERT INTO City VALUES ('', 'Faro', 193, 'EN');
INSERT INTO City VALUES ('', 'Fátima', 193, 'EN');
INSERT INTO City VALUES ('', 'Felgueiras', 193, 'EN');
INSERT INTO City VALUES ('', 'Figueira da Foz', 193, 'EN');
INSERT INTO City VALUES ('', 'Fiães', 193, 'EN');
INSERT INTO City VALUES ('', 'Freamunde', 193, 'EN');
INSERT INTO City VALUES ('', 'Funchal', 193, 'EN');
INSERT INTO City VALUES ('', 'Fundão', 193, 'EN');
INSERT INTO City VALUES ('', 'Gafanha da Nazaré', 193, 'EN');
INSERT INTO City VALUES ('', 'Gandra', 193, 'EN');
INSERT INTO City VALUES ('', 'Gondomar', 193, 'EN');
INSERT INTO City VALUES ('', 'Gouveia', 193, 'EN');
INSERT INTO City VALUES ('', 'Guarda', 193, 'EN');
INSERT INTO City VALUES ('', 'Guimarães', 193, 'EN');
INSERT INTO City VALUES ('', 'Horta', 193, 'EN');
INSERT INTO City VALUES ('', 'Ílhavo', 193, 'EN');
INSERT INTO City VALUES ('', 'Lagoa', 193, 'EN');
INSERT INTO City VALUES ('', 'Lagos', 193, 'EN');
INSERT INTO City VALUES ('', 'Lamego', 193, 'EN');
INSERT INTO City VALUES ('', 'Leiria', 193, 'EN');
INSERT INTO City VALUES ('', 'Lisbon', 193, 'EN');
INSERT INTO City VALUES ('', 'Lixa', 193, 'EN');
INSERT INTO City VALUES ('', 'Loulé', 193, 'EN');
INSERT INTO City VALUES ('', 'Loures', 193, 'EN');
INSERT INTO City VALUES ('', 'Lourosa', 193, 'EN');
INSERT INTO City VALUES ('', 'Macedo de Cavaleiros', 193, 'EN');
INSERT INTO City VALUES ('', 'Machico', 193, 'EN');
INSERT INTO City VALUES ('', 'Maia', 193, 'EN');
INSERT INTO City VALUES ('', 'Mangualde', 193, 'EN');
INSERT INTO City VALUES ('', 'Marco de Canaveses', 193, 'EN');
INSERT INTO City VALUES ('', 'Marinha Grande', 193, 'EN');
INSERT INTO City VALUES ('', 'Matosinhos', 193, 'EN');
INSERT INTO City VALUES ('', 'Mealhada', 193, 'EN');
INSERT INTO City VALUES ('', 'Mêda', 193, 'EN');
INSERT INTO City VALUES ('', 'Miranda do Douro', 193, 'EN');
INSERT INTO City VALUES ('', 'Mirandela', 193, 'EN');
INSERT INTO City VALUES ('', 'Montemor-o-Novo', 193, 'EN');
INSERT INTO City VALUES ('', 'Montijo', 193, 'EN');
INSERT INTO City VALUES ('', 'Moura', 193, 'EN');
INSERT INTO City VALUES ('', 'Odivelas', 193, 'EN');
INSERT INTO City VALUES ('', 'Olhão', 193, 'EN');
INSERT INTO City VALUES ('', 'Oliveira de Azeméis', 193, 'EN');
INSERT INTO City VALUES ('', 'Oliveira do Bairro', 193, 'EN');
INSERT INTO City VALUES ('', 'Oliveira do Hospital', 193, 'EN');
INSERT INTO City VALUES ('', 'Ourém', 193, 'EN');
INSERT INTO City VALUES ('', 'Ovar', 193, 'EN');
INSERT INTO City VALUES ('', 'Paços de Ferreira', 193, 'EN');
INSERT INTO City VALUES ('', 'Paredes', 193, 'EN');
INSERT INTO City VALUES ('', 'Penafiel', 193, 'EN');
INSERT INTO City VALUES ('', 'Peniche', 193, 'EN');
INSERT INTO City VALUES ('', 'Peso da Régua', 193, 'EN');
INSERT INTO City VALUES ('', 'Pinhel', 193, 'EN');
INSERT INTO City VALUES ('', 'Pombal', 193, 'EN');
INSERT INTO City VALUES ('', 'Ponta Delgada', 193, 'EN');
INSERT INTO City VALUES ('', 'Ponte de Sor', 193, 'EN');
INSERT INTO City VALUES ('', 'Portalegre', 193, 'EN');
INSERT INTO City VALUES ('', 'Portimão', 193, 'EN');
INSERT INTO City VALUES ('', 'Oporto', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Baleira', 193, 'EN');
INSERT INTO City VALUES ('', 'Póvoa de Santa Iria', 193, 'EN');
INSERT INTO City VALUES ('', 'Póvoa de Varzim', 193, 'EN');
INSERT INTO City VALUES ('', 'Praia da Vitória', 193, 'EN');
INSERT INTO City VALUES ('', 'Quarteira', 193, 'EN');
INSERT INTO City VALUES ('', 'Queluz', 193, 'EN');
INSERT INTO City VALUES ('', 'Rebordosa', 193, 'EN');
INSERT INTO City VALUES ('', 'Reguengos de Monsaraz', 193, 'EN');
INSERT INTO City VALUES ('', 'Ribeira Grande', 193, 'EN');
INSERT INTO City VALUES ('', 'Rio Maior', 193, 'EN');
INSERT INTO City VALUES ('', 'Rio Tinto', 193, 'EN');
INSERT INTO City VALUES ('', 'Sabugal', 193, 'EN');
INSERT INTO City VALUES ('', 'Sacavém', 193, 'EN');
INSERT INTO City VALUES ('', 'Santa Comba Dão', 193, 'EN');
INSERT INTO City VALUES ('', 'Santa Cruz', 193, 'EN');
INSERT INTO City VALUES ('', 'Santa Maria da Feira', 193, 'EN');
INSERT INTO City VALUES ('', 'Santana', 193, 'EN');
INSERT INTO City VALUES ('', 'Santarém', 193, 'EN');
INSERT INTO City VALUES ('', 'Santiago do Cacém', 193, 'EN');
INSERT INTO City VALUES ('', 'Santo Tirso', 193, 'EN');
INSERT INTO City VALUES ('', 'São João da Madeira', 193, 'EN');
INSERT INTO City VALUES ('', 'São Mamede de Infesta', 193, 'EN');
INSERT INTO City VALUES ('', 'São Salvador de Lordelo', 193, 'EN');
INSERT INTO City VALUES ('', 'Seia', 193, 'EN');
INSERT INTO City VALUES ('', 'Seixal', 193, 'EN');
INSERT INTO City VALUES ('', 'Serpa', 193, 'EN');
INSERT INTO City VALUES ('', 'Setúbal', 193, 'EN');
INSERT INTO City VALUES ('', 'Silves', 193, 'EN');
INSERT INTO City VALUES ('', 'Sines', 193, 'EN');
INSERT INTO City VALUES ('', 'Tarouca', 193, 'EN');
INSERT INTO City VALUES ('', 'Tavira', 193, 'EN');
INSERT INTO City VALUES ('', 'Tomar', 193, 'EN');
INSERT INTO City VALUES ('', 'Tondela', 193, 'EN');
INSERT INTO City VALUES ('', 'Torres Novas', 193, 'EN');
INSERT INTO City VALUES ('', 'Torres Vedras', 193, 'EN');
INSERT INTO City VALUES ('', 'Trancoso', 193, 'EN');
INSERT INTO City VALUES ('', 'Trofa', 193, 'EN');
INSERT INTO City VALUES ('', 'Valbom', 193, 'EN');
INSERT INTO City VALUES ('', 'Vale de Cambra', 193, 'EN');
INSERT INTO City VALUES ('', 'Valongo', 193, 'EN');
INSERT INTO City VALUES ('', 'Valpanços', 193, 'EN');
INSERT INTO City VALUES ('', 'Vendas Novas', 193, 'EN');
INSERT INTO City VALUES ('', 'Viana do Castelo', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila do Conde', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Franca de Xira', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Nova de Famalicão', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Nova de Foz Côa', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Nova de Gaia', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Nova de Santo André', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Real', 193, 'EN');
INSERT INTO City VALUES ('', 'Vila Real de Santo António', 193, 'EN');
INSERT INTO City VALUES ('', 'Viseu', 193, 'EN');
INSERT INTO City VALUES ('', 'Vizela', 193, 'EN');