INSERT INTO CourseArea VALUES ('', 'Ciências', 'PT');
INSERT INTO CourseArea VALUES ('', 'Saúde',	'PT');
INSERT INTO CourseArea VALUES ('', 'Tecnologias', 'PT');
INSERT INTO CourseArea VALUES ('', 'Agricultura e Recursos Naturais', 'PT');
INSERT INTO CourseArea VALUES ('', 'Arquitetura, Artes Plásticas e Design',	'PT');
INSERT INTO CourseArea VALUES ('', 'Ciências da Educação e Formação de Professores', 'PT');
INSERT INTO CourseArea VALUES ('', 'Direito, Ciências Sociais e Serviços', 'PT');
INSERT INTO CourseArea VALUES ('', 'Economia, Gestão e Contabilidade', 'PT');
INSERT INTO CourseArea VALUES ('', 'Humanidades, Secretariado e Tradução', 'PT');
INSERT INTO CourseArea VALUES ('', 'Física, Desporto e Artes do Espectáculo', 'PT');
INSERT INTO CourseArea VALUES ('', 'Sciences', 'EN');
INSERT INTO CourseArea VALUES ('', 'Health', 'EN');
INSERT INTO CourseArea VALUES ('', 'Technologies', 'EN');
INSERT INTO CourseArea VALUES ('', 'Agriculture and Natural Resources', 'EN');
INSERT INTO CourseArea VALUES ('', 'Architecture, Fine Arts and Design', 'EN');
INSERT INTO CourseArea VALUES ('', 'Education Sciences and Teacher Education', 'EN');
INSERT INTO CourseArea VALUES ('', 'Law, Social Sciences and Services', 'EN');
INSERT INTO CourseArea VALUES ('', 'Economics, Management and Accounting', 'EN');
INSERT INTO CourseArea VALUES ('', 'Humanities, Secretarial and Translation', 'EN');
INSERT INTO CourseArea VALUES ('', 'Physics, Sports and Performing Arts', 'EN');