INSERT INTO  ItemCategory VALUES ('', 'Tecnologia', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Lazer', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Desporto', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Equipamentos e Ferramentas', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Telemóveis e Tablets', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Moda', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Móveis', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Eletrodomésticos', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Literatura', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Instrumentos Musicais', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Festa e Eventos', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Outros', 'PT');
INSERT INTO  ItemCategory VALUES ('', 'Technology', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Lounge', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Sports', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Equipments & Tools', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Cellphones & Tablets', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Fashion', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Furniture', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Home Appliances', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Literature', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Musical Instruments', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Party & Events', 'EN');
INSERT INTO  ItemCategory VALUES ('', 'Others', 'EN');