INSERT INTO EducationalEstablishment VALUES  ('', 'Universidade de Aveiro',	'geral@ua.pt',	'+351 234 370 200', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior de Ciências da Informação e da Administração',	'geral@iscia.edu.pt',	'+351 234 423 045', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior de Entre Douro e Vouga',	'direccao@isvouga.pt',	'+351 256 377 550', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior de Paços de Brandão',	'geral@ispab.pt',	'+351 227 449 277', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Saúde Norte da Cruz Vermelha Portuguesa',	'secretarialicenciaturas@esscvp.eu',	'+351 213 616 790', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico de Beja',	'geral@ipbeja.pt',	'+351 284 315 000', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'ISAVE - Instituto Superior de Saúde',	'geral@isave.pt',	'+351 253 639 800', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico do Cávado e do Ave',	'geral@ipca.pt',	'+351 253 802 260', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Universidade do Minho',	'gcii@reitoria.uminho.pt',	'+351 253 601 100', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Tecnologias de Fafe',	'geral@iesfafe.pt',	'+351 253 509 000', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Educação de Fafe',	'geral@iesfafe.pt',	'+351 253 509 000', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior Artística de Guimarães'	,	'sadm@esap-gmr.com',	'+351 253 410 235', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico de Bragança',	'suporte@ipb.pt',	'+351 273 330 850', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico de Castelo Branco',	'ipcb@ipcb.pt',	'+351 272 339 600', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Universidade da Beira Interior',	'geral@ubi.pt',	'+351 275 319 700', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Universidade de Coimbra',	'gabadmin@uc.pt',	'+351 239 859 900', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico de Coimbra',	'pc@ipc.pt',	'+351 239 791 250', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior Miguel Torga',	'ismt@ismt.pt',	'+351 239 488 030', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior Bissaya Barreto',	'isbb@isbb.pt',	'+351 239 800 450', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Enfermagem de Coimbra',	'esenfc@esenfc.pt',	'+351 239 802 850', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Universitária Vasco da Gama',	'geral@euvg.pt',	'+351 239 444 444', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Universidade de Évora',	'atendimento@sac.uevora.pt',	'+351 266 760 220', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Universidade do Algarve',	'info@ualg.pt',	'+351 289 800 100', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior Manuel Teixeira Gomes',	'nfo@ismat.pt',	'+351 282 450 430', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Saúde Jean Piaget do Algarve',	'',	'+351 808 203 049', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico da Guarda',	'ipg@ipg.pt',	'+351 271 220 100', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico de Leiria',	'ipleiria@ipleiria.pt',	'+351 244 830 010', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'ISLA - Instituto Superior de Gestão e Administração de Leiria',	'info@islaleiria.pt',	'+351 244 820 650', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior D. Dinis',	'info@isdom.pt',	'+351 244 503 800', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Hotelaria e Turismo do Estoril',	'isabel.sousa@eshte.pt',	'+351 210 040 700', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Saúde do Alcoitão',	'geral@essa.pt',	'+351 214 607 450', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Educação de João de Deus',	'esse@escolasjoaodeus.pt',	'+351 213 968 154', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola do Serviço de Saúde Militar',	'info@mail.exercito.pt',	'+351 218 842 477', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Universitário Militar',	'secretaria@ium.pt',	'+351 213 002 100', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Universidade de Lisboa',	'reitoria@ulisboa.pt',	'+351 217 967 624', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior de Ciências Policiais e Segurança Interna',	'nsic.iscpsi@psp.pt',	'+351 213 613 900', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Politécnico de Lisboa',	'geral@sp.ipl.pt',	'+351 217 101 200', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Artes Decorativas',	'esad.geral@fress.pt',	'+351 218 814 696', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Educação Almeida Garrett',	'info@eseag.pt',	'+351 218 862 042', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Saúde Ribeiro Sanches',	'info@erisa.pf',	'+351 218 621 060', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'ISEC Lisboa - Instituto Superior de Educação e Ciências',	'info@iseclisboa.pt',	'+351 217 541 310', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior de Gestão',	'informacoes@isg.pt',	'+351 217 513 700', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Enfermagem de Lisboa',	'recursoshumanos@esel.pt',	'+351 217 924 100', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Academia Nacional Superior de Orquestra',	'metropolitana@metropolitana.pt',	'+351 213 617 320', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Actividades Imobiliárias',	'esai@esai.pt',	'+351 218 367 010', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Educadores de Infância Maria Ulrich',	'info.eseimu@api.edu.pt',	'+351 213 929 560', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Saúde da Cruz Vermelha Portuguesa', 'secretarialicenciaturas@esscvp.eu',	'+351 213 616 790', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Enfermagem S. Francisco das Misericórdias',	'esesfm@esesfm.pt',	'+351 217 120 913', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Escola Superior de Tecnologias e Artes de Lisboa',	'estal@estal.pt',	'+351 213 964 086', 193);
INSERT INTO EducationalEstablishment VALUES  ('', 'Instituto Superior de Novas Profissões',	'info@inp.pt',	'+351 217 548 625', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Português de Administração de Marketing de Lisboa'	,	'elpuslisboa@ipam.pt',	'+351 218 360 030', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Comunicação Empresarial'	,	'secretaria@iscem.pt',	'+351 213 474 283', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Gestão Bancária'	,	'info@isgb.pt',	'+351 217 916 210', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Ciências da Administração'	,	'info@iscad.pt',	'+351 213 261 440', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Europeia'	,	'admissions@universidadeeuropeia.pt',	'+351 808 203 544', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Lusófona de Humanidades e Tecnologias'	,	'info@ulusofona.pt',	'+351 217 515 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	ISPA-Instituto Universitário de Ciências Psicológicas, Sociais e da Vida'	,	'info@ispa.pt',	'+351 218 811 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Tecnologias Avançadas de Lisboa'	,	'secretaria@istec.pt',	'+351 218 436 670', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Lusíada'	,	'secretaria@lis.ulusiada.pt',	'+351 213 611 573', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	ISCTE - Instituto Universitário de Lisboa'	,	'geral@iscte.pt',	'+351 217 903 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa'	,	'administradora@unl.pt',	'+351 213 715 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Aberta'	,	'Maria.Carvalho@uab.pt',	'+351 213 916 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Autónoma de Lisboa Luís de Camões'	,	'geral@autonoma.pt',	'+351 213 177 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa'	,	'info@reitoria.ucp.pt',	'+351 217 214 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior Náutica Infante D. Henrique'	,	'info@enautica.pt',	'+351 214 460 010', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Atlântica - Escola Universitária de Ciências Empresariais, Saúde, Tecnologias e Engenharia'	,	'info@uatlantica.pt',	'+351 214 398 224', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Saúde Atlântica'	,	'info@uatlantica.pt',	'+351 214 398 224 ', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior Politécnico do Oeste'	,	'info@ispo.pt',	'+351 261 316 104', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Ciências Educativas'	,	'geral@isce.pt',	'+351 219 347 135', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Portalegre'	,	'geral@ipportalegre.pt',	'+351 245 301 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico da Maia'	,	'info@ipmaia.pt',	'+351 229 866 026', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Universitário da Maia - ISMAI'	,	'info@ismai.pt',	'+351 229 866 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Serviço Social do Porto'	,	'isssp@isssp.pt',	'+351 229 577 210', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Artes e Design'	,	'info@esad.pt',	'+351 229 578 750', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Universitário de Ciências da Saúde'	,	'info@cespu.pt',	'+351 255 102 813', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	CESPU-Instituto Politécnico de Saúde do Norte'	,	'info@cespu.pt',	'+351 255 102 813', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Ciências Educativas do Douro'	,	'geral@iscedouro.pt',	'+351 255 318 550', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto'	,	'ipp@ipp.pt',	'+351 225 571 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Lusíada - Norte'	,	'info@por.ulusiada.pt',	'+351 225 570 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Portucalense Infante D. Henrique'	,	'upt@upt.pt',	'+351 225 572 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto'	,	'up@up.pt',	'+351 220 408 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Educação de Paula Frassinetti'	,	'',	'+351 225 573 420', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Lusófona do Porto'	,	'info@upl.pt',	'+351 222 073 230', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Fernando Pessoa'	,	'geral@ufp.edu.pt',	'+351 225 508 269', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Saúde de Santa Maria'	,	'geral@santamariasaude.pt',	'+351 225 098 664', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Português de Administração de Marketing do Porto'	,	'admissions.porto@ipam.pt',	'+351 808 203 778', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Administração e Gestão'	,	'isag@isag.pt',	'+351 220 303 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Ciências Empresariais e do Turismo'	,	'iscet@iscet.pt',	'+351 222 053 685', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Enfermagem do Porto'	,	'esep@esenf.pt',	'+351 225 073 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior Artística do Porto'	,	'geral@esap.pt',	'+351 223 392 130', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	ISLA - Instituto Politécnico de Gestão e Tecnologia'	,	'info@islagaia.pt',	'+351 223 772 980', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior Politécnico Gaya'	,	'info@ispgaya.pt',	'+351 223 745 730', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Educação Jean Piaget de Arcozelo'	,	'info@gaia.ipiaget.pt',	'+365 227 536 620', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Negócios Atlântico'	,	'info@iesf.pt',	'+351 227 538 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Saúde Jean Piaget de Vila Nova de Gaia'	,	'info@gaia.ipiaget.pt',	'+365 227 536 620', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Conservatório Superior de Música de Gaia'	,	'regional@conservatoriodegaia.org',	'+351 223 712 213', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Santarém'	,	'geral@ipsantarem.pt',	'+351 243 309 520', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	ISLA - Instituto Superior de Gestão e Administração de Santarém'	,	'info@islasantarem.pt',	'+351 243 305 880', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Tomar'	,	'gape@ipt.pt',	'+351 249 328 216', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Saúde Egas Moniz'	,	'egasmoniz@egasmoniz.edu.pt',	'+351 212 946 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Universitário Egas Moniz'	,	'egasmoniz@egasmoniz.edu.pt',	'+351 212 946 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Educação Jean Piaget de Almada'	,	'info@almada.ipiaget.pt',	'+351 212 946 250', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Tecnologia e Gestão Jean Piaget'	,	'info@almada.ipiaget.pt',	'+351 212 946 250', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Estudos Interculturais e Transdisciplinares de Almada'	,	'info@almada.ipiaget.pt',	'+351 212 946 250', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Setúbal'	,	'info@ese.ips.pt',	'+351 265 710 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viana do Castelo'	,	'geral@ipvc.pt',	'+351 258 809 610', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior Gallaecia'	,	'esg@esg.pt',	'+351 251 794 054', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Enfermagem Dr. José Timóteo Montalvão Machado'	,	'info@esechaves.pt',	'+351 276 301 690', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Trás-os-Montes e Alto Douro'	,	'',	'+351 259 350 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viseu'	,	'ipv@sc.ipv.pt',	'+351 232 480 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Estudos Interculturais e Transdisciplinares de Viseu'	,	'info@viseu.ipiaget.pt',	'+351 232 910 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Saúde Jean Piaget de Viseu'	,	'info@viseu.ipiaget.pt',	'+351 232 910 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Escola Superior de Enfermagem de S. José de Cluny'	,	'geral@esesjcluny.pt',	'+351 291 743 444', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade da Madeira'	,	'gabinetedareitoria@uma.pt',	'+351 291 209 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior de Administração e Línguas'	,	'isal@isal.pt',	'+351 291 705 705', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores'	,	'svga.expediente@uac.pt',	'+351 296 650 032', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Aveiro - Escola Superior de Tecnologia e Gestão de Águeda'	,	'estga.geral@ua.pt',	'+351 234 370 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Aveiro - Instituto Superior de Contabilidade e Administração de Aveiro'	,	'isca.geral@ua.pt',	'+351 234 370 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Aveiro - Escola Superior de Saúde de Aveiro'	,	'essua.secretaria@ua.pt',	'+351 234 370 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Aveiro - Escola Superior de Design, Gestão e Tecnologias da Produção de Aveiro-Norte'	,	'esan.geral@ua.pt',	'+351 234 370 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Beja - Escola Superior de Tecnologia e de Gestão'	,	'direccao.estig@ipbeja.pt',	'+351 284 311 540', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Beja - Escola Superior de Saúde'	,	'ess@ipbeja.pt',	'+351 284 313 280', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Beja - Escola Superior Agrária'	,	'esa@ipbeja.pt',	'+351 284 314 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Beja - Escola Superior de Educação'	,	'ese@ipbeja.pt',	'+351 284 315 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Cávado e do Ave - Escola Superior de Design'	,	'esd@ipca.pt',	'+351 253 802 266', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Cávado e do Ave - Escola Superior de Hotelaria e Turismo'	,	'esht@ipca.pt',	'+351 253 802 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Cávado e do Ave - Escola Superior de Gestão'	,	'geral@ipca.pt',	'+351 253 802 190', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Cávado e do Ave - Escola Superior de Tecnologia'	,	'est@ipca.pt',	'+351 253 802 260', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Filosofia e Ciências Sociais'	,	'secretaria.ffcs@braga.ucp.pt',	'+351 253 201 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Teologia (Braga)'	,	'secretaria.facteo@braga.ucp.pt',	'+351 253 206 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Minho - Escola Superior de Enfermagem'	,	'sec.presidencia@ese.uminho.​pt',	'+351 253 601 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Lusíada - Norte - Vila Nova de Famalicão'	,	'info@fam.ulusiada.pt',	'+351 252 309 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	CESPU-Instituto Politécnico de Saúde do Norte - Escola Superior de Saúde do Vale do Ave'	,	'dir.iucs@cespu.pt',	'+351 224 157 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Bragança - Escola Superior de Tecnologia e de Gestão de Bragança'	,	'estig@ipb.pt',	'+351 273 303 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Bragança - Escola Superior de Saúde de Bragança'	,	'essa@ipb.pt',	'+351 273 330 950', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Bragança - Escola Superior Agrária de Bragança'	,	'grei@ipb.pt',	'+351 273 303 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Bragança - Escola Superior de Educação de Bragança'	,	'giape@ipb.pt',	'+351 273 303 390', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Bragança - Escola Superior de Comunicação, Administração e Turismo de Mirandela'	,	'esact@ipb.pt',	'+351 278 201 340', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Castelo Branco - Escola Superior de Tecnologia de Castelo Branco'	,	'est@ipcb.pt',	'+351 272 339 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Castelo Branco - Escola Superior de Saúde Dr. Lopes Dias'	,	'esald@ipcb.pt',	'+351 272 340 560', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Castelo Branco - Escola Superior Agrária de Castelo Branco'	,	'esa@ipcb.pt',	'+351 272 339 900', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Castelo Branco - Escola Superior de Educação de Castelo Branco'	,	'ese@ipcb.pt',	'+351 272 339 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Castelo Branco - Escola Superior de Artes Aplicadas de Castelo Branco'	,	'esart@ipcb.pt',	'+351 272 340 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Castelo Branco - Escola Superior de Gestão de Idanha-a-Nova'	,	'esg@ipcb.pt',	'+351 277 200 220', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Coimbra - Escola Superior de Educação de Coimbra'	,	'presidente@esec.pt',	'+351 239 793 120', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Colégio das Artes'	,	'colegiodasartes@colegiodasartes.uc.pt',	'+351 239 857 019', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Instituto de Investigação Interdisciplinar'	,	'iii@uc.pt',	'+351 239 247 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Farmácia'	,	'ffuc@ff.uc.pt',	'+351 239 488 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Ciências do Desporto e Educação Física'	,	'gd@fcdef.uc.pt',	'+351 239 802 770', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Coimbra - Escola Superior de Tecnologia da Saúde de Coimbra'	,	'geral@estescoimbra.pt',	'+351 239 802 430', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Coimbra - Escola Superior Agrária de Coimbra'	,	'academicos@esac.pt ',	'+351 239 802 940', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Coimbra - Instituto Superior de Contabilidade e Administração de Coimbra'	,	'geral@iscac.pt',	'+351 239 802 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Coimbra - Instituto Superior de Engenharia de Coimbra'	,	'info@isec.pt',	'+351 239 790 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Ciências e Tecnologia'	,	'fctuc@fct.uc.pt',	'+351 239 700 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Direito'	,	'fduc@fd.uc.pt',	'+351 239 859 802', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Economia'	,	'feuc@fe.uc.pt',	'+351 239 790 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Letras'	,	'saari@fl.uc.pt',	'+351 239 859 991', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Medicina'	,	'direcao@fmed.uc.pt',	'+351 239 857 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Coimbra - Faculdade de Psicologia e de Ciências da Educação'	,	'dir@fpce.uc.pt',	'+351 239 851 450', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Coimbra - Escola Superior de Tecnologia e Gestão de Oliveira do Hospital'	,	'geral@estgoh.ipc.pt',	'+351 238 605 170', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Évora - Instituto de Investigação e Formação Avançada'	,	'geral@iifa.uevora.pt',	'+351 266 740 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Évora - Escola de Ciências e Tecnologia'	,	'geral@ect.uevora.pt',	'+351 266 740 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Évora - Escola de Artes'	,	'geral@ea.uevora.pt',	'+351 266 760 260', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Évora - Escola de Ciências Sociais'	,	'cl@ecs.uevora.pt',	'+351 266 740 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Évora - Escola Superior de Enfermagem de São João de Deus'	,	'geral@esesjd.uevora.pt',	'+351 266 730 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Escola Superior de Saúde'	,	'essualg@ualg.pt',	'+351 289 800 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Escola Superior de Educação e Comunicação'	,	'esecsec@ualg.pt',	'+351 289 800 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Escola Superior de Gestão, Hotelaria e Turismo'	,	'diretoresght@ualg.pt',	'+351 289 800 136', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Instituto Superior de Engenharia'	,	'ise@ualg.pt',	'+351 289 800 124', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Faculdade de Ciências Humanas e Sociais'	,	'info@ualg.pt',	'+351 289 800 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Faculdade de Ciências e Tecnologia'	,	'fct@ualg.pt',	'+351 289 800 905', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Faculdade de Economia'	,	'diretorfeualg@ualg.pt',	'+351 289 800 915', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Algarve - Escola Superior de Gestão, Hotelaria e Turismo (Portimão)'	,	'coordenadorptmesght@ualg.pt',	'+351 282 417 641', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico da Guarda - Escola Superior de Saúde da Guarda'	,	'ess.geral@ipg.pt',	'+351 271 205 220', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico da Guarda - Escola Superior de Educação, Comunicação e Desporto'	,	'esecd-geral@ipg.pt',	'+351 271 220 135', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico da Guarda - Escola Superior de Tecnologia e Gestão'	,	'estg-geral@ipg.pt',	'+351 271 220 164', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico da Guarda - Escola Superior de Turismo e Hotelaria'	,	'eral.esth@ipg.pt',	'+351 238 320 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Leiria - Escola Superior de Artes e Design das Caldas da Rainha'	,	'esad@esad.ipleiria.pt',	'+351 262 830 900', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Leiria - Escola Superior de Saúde de Leiria'	,	'esslei@ipleiria.pt',	'+351 244 845 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Leiria - Escola Superior de Educação e Ciências Sociais'	,	'ipleiria@ipleiria.pt',	'+351 244 830 010', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Leiria - Escola Superior de Tecnologia e Gestão'	,	'estg@estg.ipleiria.pt',	'+351 244 820 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Leiria - Escola Superior de Turismo e Tecnologia do Mar de Peniche'	,	'estm@ipleiria.pt',	'+351 262 783 607', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Instituto Superior de Estatística e Gestão de Informação'	,	'apoioaluno@novaims.unl.pt',	'+351 213 828 610', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Escola Superior de Música'	,	'esml@esml.ipl.pt',	'+351 210 464 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Instituto de Ciências da Saúde'	,	'saude@porto.ucp.pt',	'+351 226 196 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Universitário Militar - Academia Militar'	,	'secretaria@ium.pt',	'+351 213 002 103', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Universitário Militar - Unidade Politécnica Militar'	,	'secretaria@ium.pt',	'+351 213 025 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Arquitectura'	,	'recursoshumanos@fa.ulisboa.pt',	'+351 213 615 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Teologia'	,	'direccao@ft.lisboa.ucp.pt',	'+351 217 214 150', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Escola Superior Politécnica de Saúde (Lisboa)'	,	'saude@ics.lisboa.ucp.pt',	'+351 217 214 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Faculdade de Direito'	,	'direccao.direito@fd.lisboa.ucp.pt',	'+351 217 214 170', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Instituto de Estudos Políticos'	,	'info.iep@iep.lisboa.ucp.pt',	'+351 217 214 129', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Faculdade de Ciências Médicas'	,	'academicos@nms.unl.pt',	'+351 218 803 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Faculdade de Ciências Sociais e Humanas'	,	'geral@fcsh.unl.pt',	'+351 21 790 83 00', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Faculdade de Economia'	,	'infonova@novasbe.pt',	'+351 213 801 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Instituto de Higiene e Medicina Tropical'	,	'geral@ihmt.unl.pt',	'+351 213 652 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Escola Nacional de Saúde Pública'	,	'geral@ensp.unl.pt',	'+351 217 512 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Ciências Humanas'	,	'direcaofch@fch.lisboa.ucp.pt',	'+351 217 214 190', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Escola Superior de Educação de Lisboa'	,	'eselx@eselx.ipl.pt',	'+351 217 115 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Escola Superior de Comunicação Social'	,	'servicos_academicos@escs.ipl.pt',	'+351 217 119 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Instituto Superior de Contabilidade e Administração de Lisboa'	,	'iscal@iscal.ipl.pt',	'+351 217 984 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Instituto Superior de Engenharia de Lisboa'	,	'geral@sp.ipl.pt',	'+351 218 317 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Ciências Económicas e Empresariais'	,	'',	'+351 217 270 250', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Direito'	,	'direccao.direito@fd.lisboa.ucp.pt',	'+351 217 214 170', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto Superior de Agronomia'	,	'cgisa@isa.ulisboa.pt',	'+351 213 653 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Escola Superior de Tecnologia da Saúde de Lisboa'	,	'comunidade@estesl.ipl.pt',	'+351 218 980 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto Superior de Ciências Sociais e Políticas'	,	'geral@iscsp.ulisboa.pt',	'+351 213 619 430', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto Superior de Economia e Gestão'	,	'seclic@iseg.ulisboa.pt',	'+351 213 925 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto Superior Técnico'	,	'mail@tecnico.ulisboa.pt',	'+351 218 417 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Escola Superior de Dança'	,	'geral@esd.ipl.pt',	'+351 213 244 770', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Medicina Dentária'	,	'geral@fmd.ulisboa.pt',	'+351 217 922 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Medicina Veterinária'	,	'fmv@fmv.ulisboa.pt',	'+351 213 652 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Psicologia'	,	'geral@psicologia.ulisboa.pt',	'+351 217 943 655', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto de Ciências Sociais'	,	'instituto.ciencias.sociais@ics.ulisboa.pt',	'+351 217 804 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto de Geografia e Ordenamento do Território'	,	'igot@ulisboa.pt',	'+351 210 443 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto de Educação'	,	'geral@ie.ulisboa.pt',	'+351 217 943 633', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Belas-Artes'	,	'academicos@belasartes.ulisboa.pt',	'+351 213 252 100 ', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Ciências'	,	'info@ciencias.ulisboa.pt',	'+351 217 500 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Direito'	,	'secretariadodir@fd.ulisboa.pt',	'+351 217 984 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Farmácia'	,	'geral@ff.ulisboa.pt',	'+351 217 946 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Letras'	,	'info@letras.ulisboa.pt',	'+351 217 920 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Medicina'	,	'fmul@medicina.ulisboa.pt',	'+351 217 985 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Faculdade de Motricidade Humana'	,	'fmh@fmh.ulisboa.pt',	'+351 214 149 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Lisboa - Instituto Superior Técnico (Taguspark)'	,	'mail@tecnico.ulisboa.pt',	'+351 214 233 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Instituto de Tecnologia Química e Biológica António Xavier'	,	'info@itqb.unl.pt',	'+351 214 469 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Universitário Militar - Academia da Força Aérea'	,	'secretaria@ium.pt',	'+351 213 002 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Lisboa - Escola Superior de Teatro e Cinema'	,	'estc@estc.ipl.pt',	'+351 214 989 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Portalegre - Escola Superior Agrária de Elvas'	,	'esae@esaelvas.pt',	'+351 268 628 528', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Portalegre - Escola Superior de Saúde'	,	'geral@essp.pt',	'+351 245 300 430', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Portalegre - Escola Superior de Educação  e Ciências Sociais'	,	'esep@esep.pt',	'+351 245339400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Portalegre - Escola Superior de Tecnologia e Gestão'	,	'estg@estgp.pt',	'+351 245 300 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Escola Superior de Tecnologia e Gestão'	,	'correio@estg.ipp.pt',	'+351 255 314 002', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico da Maia - Escola Superior de Ciências Sociais, Educação e Desporto'	,	'info@ipmaia.pt',	'+351 229 866 026', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico da Maia - Escola Superior de Tecnologia e Gestão'	,	'info@ipmaia.pt',	'+351 229 866 026', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Instituto Superior de Contabilidade e Administração do Porto'	,	'instituto@iscap.ipp.pt',	'+351 229 050 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	CESPU-Instituto Politécnico de Saúde do Norte - Escola Superior de Saúde do Vale do Sousa'	,	'info@cespu.pt',	'+351 255 102 813', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Engenharia'	,	'spregrad@fe.up.pt ',	'+351 225 081 405', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Direito (Porto)'	,	'comunicacao@porto.ucp.pt',	'+351 226 196 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Lusíada - Norte - Porto'	,	'info@por.ulusiada.pt',	'+351 225 570 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Direito'	,	'fdup@direito.up.pt',	'+351 222 041 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Escola Superior de Educação'	,	'esse@ese.ipp.pt',	'+351 225 073 460', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Escola Superior de Música e das Artes do Espectáculo'	,	'esmae@esmae.ipp.pt',	'+351 225 193 760', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Educação e Psicologia'	,	'dnoverca@porto.ucp.pt',	'+351 226 196 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Fernando Pessoa - Escola Superior de Saúde'	,	'geral@ufp.edu.pt',	'+351 225 071 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Instituto de Bioética'	,	'ib@porto.ucp.pt',	'+351 226 196 216', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Escola das Artes'	,	'artes@porto.ucp.pt',	'+351 226 196 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Instituto de Ciências Biomédicas Abel Salazar'	,	'divulgacao@icbas.up.pt',	'+351 220 428 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Desporto'	,	'expediente@fade.up.pt',	'+351 220 425 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Medicina Dentária'	,	'aprovisionamento@fmd.up.pt',	'+351 220 901 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Escola Superior de Biotecnologia'	,	'comunicacao@porto.ucp.pt',	'+351 225 580 001', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Escola Superior Politécnica de Saúde (Porto)'	,	'saude@porto.ucp.pt',	'+351 226 196 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Instituto de Ciências da Saúde (Porto)'	,	'info@viseu.ucp.pt',	'+351 232 419 506', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Ciências'	,	'apoio.estudante@fc.up.pt',	'+351 220 402 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Economia'	,	'geral@fep.up.pt',	'+351 225 571 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Farmácia'	,	'ffup@ff.up.pt',	'+351 220 428 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Letras'	,	'flup@letras.up.pt',	'+351 226 077 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Medicina'	,	'fmupatmed.up.pt',	'+351 225 513 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Psicologia e de Ciências da Educação'	,	'fpce@fpce.up.pt',	'+351 226 079 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Instituto Superior de Engenharia do Porto'	,	'mail@isep.ipp.pt',	'+351 228 340 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Teologia (Porto)'	,	'comunicacao@porto.ucp.pt',	'+351 226 196 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Faculdade de Economia e Gestão'	,	'comunicacao@porto.ucp.pt',	'+351 226 196 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Belas Artes'	,	'expediente@fba.up.pt',	'+351 225 192 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Ciências da Nutrição e da Alimentação'	,	'webmaster@fcna.up.pt',	'+351 225 074 320', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade do Porto - Faculdade de Arquitetura'	,	'comunicacao@arq.up.pt',	'+351 226 057 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Escola Superior de Hotelaria e Turismo'	,	'geral@esht.ipp.pt',	'+351 252 291 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Escola Superior de Media Artes e Design'	,	'geral@esmad.ipp.pt',	'+351 252 291 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico do Porto - Escola Superior de Saúde do Porto'	,	'geral@ess.ipp.pt',	'+351 222 061 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	ISLA - Instituto Politécnico de Gestão e Tecnologia - Escola Superior de Gestão'	,	'info@islagaia.pt',	'+351 223 772 980', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	ISLA - Instituto Politécnico de Gestão e Tecnologia - Escola Superior de Tecnologia'	,	'info@islagaia.pt',	'+351 223 772 980', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior Politécnico Gaya - Escola Superior de Desenvolvimento Social e Comunitário'	,	'info@ispgaya.pt',	'+351 223 745 730', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Superior Politécnico Gaya - Escola Superior de Ciência e Tecnologia'	,	'info@ispgaya.pt',	'+351 223 745 730', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Tomar - Escola Superior de Tecnologia de Abrantes'	,	'esta@ipt.pt',	'+351 241 379 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Santarém - Escola Superior de Desporto de Rio Maior'	,	'geral@esdrm.ipsantarem.pt',	'+351 243 999 280', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Santarém - Escola Superior Agrária de Santarém'	,	'info@esa.ipsantarem.pt',	'+351 243 307 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Santarém - Escola Superior de Saúde de Santarém'	,	'geral@essaude.ipsantarem.pt',	'+351 243 307 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Santarém - Escola Superior de Educação de Santarém'	,	'geral@ese.ipsantarem.pt',	'+351 243 309 180', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Santarém - Escola Superior de Gestão e Tecnologia de Santarém'	,	'correio@esg.ipsantarem.pt',	'+351 243 303 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Tomar - Escola Superior de Gestão de Tomar'	,	'esgt@ipt.pt',	'+351 249 328 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Tomar - Escola Superior de Tecnologia de Tomar'	,	'estt@ipt.pt',	'+351 249 328 217', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Universitário Militar - Escola Naval'	,	'escnaval-escolanaval.geral@marinha.pt',	'+351 808 201 467', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Nova de Lisboa - Faculdade de Ciências e Tecnologia'	,	'div.a.ae.mobilidade@fct.unl.pt',	'+351 212 948 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Setúbal - Escola Superior de Tecnologia do Barreiro'	,	'info@estbarreiro.ips.pt',	'+351 212 064 660', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Setúbal - Escola Superior de Educação'	,	'diretora@ese.ips.pt',	'+351 265 710 800', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Setúbal - Escola Superior de Tecnologia de Setúbal'	,	'info@estsetubal.ips.pt',	'+351 265 548 820', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Setúbal - Escola Superior de Ciências Empresariais'	,	'info@esce.ips.pt',	'+351 265 709 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Setúbal - Escola Superior de Saúde'	,	'info@ess.ips.pt',	'+351 265 709 300', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viana do Castelo - Escola Superior de Desporto e Lazer de Melgaço'	,	'geral@esdl.ipvc.pt',	'+351 258 809 678', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viana do Castelo - Escola Superior Agrária'	,	'geral@esa.ipvc.pt',	'+351 258 909 740', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Fernando Pessoa (unidade de Ponte de Lima - ensino Politécnico)'	,	'geral.plima@ufp.edu.pt',	'+351 258 741 026', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Fernando Pessoa (unidade de Ponte de Lima)'	,	'geral.plima@ufp.edu.pt',	'+351 258 741 026', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viana do Castelo - Escola Superior de Ciências Empresariais'	,	'geral@esce.ipvc.pt',	'+351 258 809 679', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viana do Castelo - Escola Superior de Saúde de Viana do Castelo'	,	'geral@ess.ipvc.pt',	'+351 258 809 550', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viana do Castelo - Escola Superior de Educação'	,	'geral@ese.ipvc.pt',	'+351 258 806 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viana do Castelo - Escola Superior de Tecnologia e Gestão'	,	'direcao@estg.ipvc.pt',	'+351 258 819 700', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Trás-os-Montes e Alto Douro - Escola de Ciências Humanas e Sociais (Chaves)'	,	'sechs@utad.pt',	'+351 259 350 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Trás-os-Montes e Alto Douro - Escola de Ciências Agrárias e Veterinárias'	,	'sautad@utad.pt',	'+351 259 350 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Trás-os-Montes e Alto Douro - Escola de Ciências Humanas e Sociais'	,	'sautad@utad.pt',	'+351 259 350 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Trás-os-Montes e Alto Douro - Escola de Ciências e Tecnologia'	,	'sautad@utad.pt',	'+351 259 350 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Trás-os-Montes e Alto Douro - Escola de Ciências da Vida e do Ambiente'	,	'sautad@utad.pt',	'+351 259 350 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade de Trás-os-Montes e Alto Douro - Escola Superior de Saúde'	,	'sautad@utad.pt',	'+351 259 350 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viseu - Escola Superior de Tecnologia e Gestão de Lamego'	,	'estgl@estgl.ipv.pt',	'+351 254 615 477', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Escola Superior Politécnica de Saúde (Viseu)'	,	'info@viseu.ucp.pt',	'+351 232 419 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viseu - Escola Superior de Saúde de Viseu'	,	'essvgeral@essv.ipv.pt',	'+351 232 419 100', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade Católica Portuguesa - Centro Regional das Beiras'	,	'info@viseu.ucp.pt',	'+351 232 419 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viseu - Escola Superior de Educação de Viseu'	,	'esev@esev.ipv.pt',	'+351 232 419 000', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viseu - Escola Superior de Tecnologia e Gestão de Viseu'	,	'estgv@estgv.ipv.pt',	'+351 232 480 500', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Instituto Politécnico de Viseu - Escola Superior Agrária de Viseu'	,	'esav@esav.ipv.pt',	'+351 232 446 600', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade da Madeira - Faculdade de Artes e Humanidades'	,	'recursoshumanos@uma.pt ',	'+351 291 209 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade da Madeira - Faculdade de Ciências Exatas e da Engenharia'	,	'recursoshumanos@uma.pt ',	'+351 291 209 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade da Madeira - Faculdade de Ciências Sociais'	,	'recursoshumanos@uma.pt ',	'+351 291 209 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade da Madeira - Faculdade de Ciências da Vida'	,	'recursoshumanos@uma.pt ',	'+351 291 209 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade da Madeira - Escola Superior de Saúde'	,	'recursoshumanos@uma.pt ',	'+351 291 209 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade da Madeira - Escola Superior de Tecnologias e Gestão'	,	'recursoshumanos@uma.pt ',	'+351 291 209 400', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Escola Superior de Saúde - Ponta Delgada'	,	'svga.expediente@uac.pt',	'+351 296 650 032', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Escola Superior de Tecnologias - Ponta Delgada'	,	'svga.expediente@uac.pt',	'+351 296 650 032', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Faculdade de Ciências Sociais e Humanas'	,	'svga.expediente@uac.pt',	'+351 296 650 032', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Faculdade de Ciências e Tecnologia'	,	'svga.expediente@uac.pt',	'+351 296 650 032', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Faculdade de Economia e Gestão'	,	'svga.expediente@uac.pt',	'+351 296 650 032', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Escola Superior de Saúde - Angra do Heroísmo'	,	'svga.expediente@uac.pt',	'+351 295 402 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Escola Superior de Tecnologias - Angra do Heroísmo'	,	'svga.expediente@uac.pt',	'+351 295 402 200', 193);
INSERT INTO EducationalEstablishment VALUES 	('',	'	Universidade dos Açores - Faculdade de Ciências Agrárias e do Ambiente'	,	'svga.expediente@uac.pt',	'+351 296 650 032', 193);