INSERT	INTO Nationality VALUES	('', 'Afghan', 'EN');
INSERT	INTO Nationality VALUES	('', 'Albanian', 'EN');
INSERT	INTO	Nationality	VALUES	('', 'Algerian', 'EN');
INSERT	INTO	Nationality	VALUES	('', 'American', 'EN');
INSERT	INTO	Nationality	VALUES	('', 'Andorran', 'EN');
INSERT	INTO	Nationality	VALUES	('', 'Angolan',	'EN');
INSERT	INTO	Nationality	VALUES	('', 'Antiguans Barbudans',	'EN');
INSERT	INTO	Nationality	VALUES	('', 'Argentinean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Armenian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Australian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Austrian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Azerbaijani',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bahamian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bahraini',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bangladeshi',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Barbadian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Belarusian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Belgian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Belizean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Beninese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bhutanese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bolivian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bosnian Herzegovinian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Brazilian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'British',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bruneian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Bulgarian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Burkinabe',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Burmese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Burundian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Cambodian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', 'Cameroonian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Canadian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Cape Verdian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Central African',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Chadian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Chilean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Chinese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Colombian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Comoran',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Congolese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Costa Rican',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Croatian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Cuban',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Cypriot',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Czech',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Danish',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Djibouti',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Dominican',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Dominican',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Dutch',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	East Timorese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Ecuadorean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Egyptian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Emirian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Equatorial Guinean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Eritrean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Estonian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Ethiopian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Fijian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Filipino',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Finnish',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	French',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Gabonese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Gambian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Georgian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	German',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Ghanaian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Greek',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Grenadian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Guatemalan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Guinea-Bissauan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Guinean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Guyanese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Haitian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Honduran',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Hungarian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	I-Kiribati',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Icelander',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Indian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Indonesian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Iranian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Iraqi',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Irish',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Israeli',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Italian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Ivorian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Jamaican',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Japanese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Jordanian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Kazakhstani',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Kenyan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Kirghiz',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Kittian and	Nevisian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Kuwaiti',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Laotian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Latvian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Lebanese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Liberian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Libyan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Liechtensteiner',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Lithuanian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Luxembourger',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Macedonian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Malagasy',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Malawian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Malaysian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Maldivan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Malian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Maltese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Marshallese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Mauritanian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Mauritian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Mexican',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Micronesian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Moldovan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Monegasque',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Mongolian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Moroccan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Mosotho',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Motswana',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Mozambican',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Namibian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Nauruan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Nepalese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	New Zealander',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Ni-Vanuatu',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Nicaraguan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Nigerian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Nigerien',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	North Korean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Norwegian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Omani',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Pakistani',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Palauan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Panamanian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Papua New	Guinean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Paraguayan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Peruvian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Polish',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Portuguese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Qatari',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Romanian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Russian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Rwandan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Saint Lucian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Salvadoran',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Sammarinese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Samoan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	São Tomean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Saudi Arabian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Senegalese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Serbian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Seychellois',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Sierra Leonean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Singaporean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Slovak',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Slovene',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Solomon Islander',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Somali',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	South African',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	South Korean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Spanish',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Sri Lankan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Sudanese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Surinamer',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Swazi',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Swedish',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Swiss',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Syrian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Tadzhik',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Taiwanese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Tanzanian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Thai',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Togolese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Tongan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Trinidadian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Tunisian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Turkish',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Turkmen',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Tuvaluan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Ugandan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Ukrainian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Uruguayan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Uzbekistani',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Venezuelan',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Vietnamese',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Yemeni',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Zambian',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Zimbabwean',	'	EN');
INSERT	INTO	Nationality	VALUES	('', '	Afegão',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Africano do Centro',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Albanês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Alemão',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Algeriano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Americano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Andorreno',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Angolano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Antigas Barbudas',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Argentino',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Arménio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Australiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Austríaco',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Azerbaijanês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Bahamense',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Bahraini',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Balizeano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Barbadense',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Belgo',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Bengalis',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Beninese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Bielorusso',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Boliviano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Bósnio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Brasileiro',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Bruneian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Búlgaro',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Burmese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Burquinabé',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Burundo',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Butanês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Cabo Verdiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Camaronês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Cambojano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Canadiense',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Chadian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Checo',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Chileno',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Chinês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Cipriota',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Colombiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Comoran',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Congolese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Costa Riquenho',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Croata',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Cubano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Dinamarquês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Djibouti',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Dominican',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Dominican',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	East Timorese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Ecuadorean',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Egípcio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Emirian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Equatorial Guinean',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Eritrean',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Eslóvaco',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Eslóveno',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Espanhol',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Estonian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Ethiopian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Fijian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Filipino',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Finlandês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Francês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Gabonese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Gambian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Georgiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Ghanaian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Grego',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Grenadian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Guatemalan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Guinea-Bissauan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Guiniense',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Guyanese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Haitian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Holandês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Honduran',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Húngaro',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	I-Kiribati',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Indiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Indonésio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Inglês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Iraniano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Iraquiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Irlandês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Islândia',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Israelita',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Italiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Ivorian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Jamaicano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Japonês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Jordão',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Kazakhstani',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Kenyan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Kirghiz',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Kittian and	Nevisian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Kuwaiti',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Laotian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Letão',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Libanês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Libanês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Liberian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Liechtensteiner',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Lituano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Luxemburguês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Macedônio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Malagasy',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Maláio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Malawian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Maldivan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Malian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Maltese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Marshallese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Mauritanian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Mauritian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Mexicano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Micronesian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Moçambicano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Moldavo',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Monegasque',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Mongolian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Moroccan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Mosotho',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Motswana',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Namibian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Nauruan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Neozelandês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Nepalês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Ni-Vanuatu',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Nicaraguan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Nigeriano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Norte Coreano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Norueguês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Omani',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Palauan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Panamanian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Papua New	Guinean',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Paquistanês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Paraguaio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Peruano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Polaco',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Português',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Qatari',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Romeno',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Russo',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Rwandan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Saint Lucian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Salvadoran',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sammarinese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Samoan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	São Tomense',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Saudi Arabian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Senegalese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Serra Leonês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sérvio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Seychellois',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Singaporean',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sírio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Solomon Islander',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sri Lankan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sudanês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sueco',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Suiço',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sul Africano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sul Coreano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Sumaliano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Surinamer',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Swazi',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Tadzhik',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Tailandês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Taiwanese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Tanzanian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Togolese',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Tongan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Trinidadian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Tunisiano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Turco',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Turkmen',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Tuvaluan',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Ucrâniano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Uganês',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Uruguaio',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Uzbekistani',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Venezuelano',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Vietenamita',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Yemeni',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Zambian',	'	PT');
INSERT	INTO	Nationality	VALUES	('', '	Zimbabwean',	'	PT');